### ISSUE TITLE
Modify css of button.

### ISSUE THREAD

**Issue by im-ankitjais** [im-ankitjais/Giphy-Search-Engine#2]

**Comment by guillaumepn** [comment]
Hi, I could work on this, what design do you imagine, do you have instructions / ideas ? I could try a design inspired by the Giphy website

**Comment by im-ankitjais** [comment]
Hi @guillaumepn ,thanks for showing interest. You may modify css as per your choice in heading and "Go" button. If it seems to be nice, I will definitely merge it.

**Comment by guillaumepn** [comment]
Alright, here is my try ! https://github.com/im-ankitjais/Giphy-Search-Engine/pull/5
